try:
    a = 1
    print(b)
except:
    print('caught error')
    print(a)
